import {
  course1,course2,course3
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Courses",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Blog",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: course1,
    courseName: "Web Development",
    price: "35.00",
    percentage:"50",
    status: "Completed",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: course2,
    courseName: "Flutter Development",
    price: "180.00",
    percentage:"55",
    status: "In Progress",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: course3,
    courseName: "Android Development",
    price: "25.00",
    percentage:"60",
    status: "In Progress",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: course1,
    courseName: "Swift Development",
    price: "220.00",
    percentage:"65",
    status: "Completed",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: course2,
    courseName: "Web Development",
    price: "4000.00",
    percentage:"70",
    status: "Open",
    color: "John Doe",
    badge: true,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: course3,
    courseName: "App Development",
    price: "180.00",
    percentage:"20",
    status: "In Progress",
    color: "John Doe",
    badge: true,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: course1,
    courseName: "Android Development",
    price: "25.00",
    percentage:"30",
    color: "John Doe",
    status: "Closed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: course2,
    courseName: "Swift Development",
    price: "220.00",
    percentage:"40",
    status: "In Progress",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: course3,
    courseName: "Web Development",
    price: "35.00",
    percentage:"50",
    status: "Open",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: course1,
    courseName: "Web Development",
    price: "180.00",
    percentage:"35",
    status: "In Progress",
    color: "John Doe",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: course2,
    courseName: "Web Development",
    price: "25.00",
    percentage:"45",
    status: "Closed",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: course3,
    courseName: "Web Development",
    price: "220.00",
    percentage:"25",
    status: "In Progress",
    color: "John Doe",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: course1,
    courseName: "Web Development",
    price: "44.00",
    percentage:"30",
    status: "Open",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: course2,
    courseName: "Web Development",
    price: "250.00",
    percentage:"60",
    status: "Closed",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: course3,
    courseName: "Web Development",
    price: "80.00",
    percentage:"70",
    status: "In Progress",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: course1,
    courseName: "Web Development",
    price: "60.00",
    percentage:"90",
    status: "Open",
    color: "John Doe",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: course2,
    courseName: "Web Development",
    price: "60.00",
    percentage: "45",
    status: "Closed",
    color: "John Doe",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1014,
    img: course3,
    courseName: "Web Development",
    price: "250.00",
    percentage:"100",
    status: "In Progress",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: course1,
    courseName: "Web Development",
    price: "60.00",
    status: "Open",
    percentage:"25",
    color: "John Doe",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: course2,
    courseName: "Web Development",
    price: "250.00",
    percentage:"42",
    status: "Closed",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: course3,
    courseName: "Web Development",
    price: "220.00",
    percentage:"65",
    status: "In Progess",
    color: "John Doe",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: course1,
    courseName: "Web Development",
    price: "44.00",
    percentage:"70",
    status: "Open",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: course2,
    courseName: "Web Development",
    price: "250.00",
    percentage:"85",
    status: "Closed",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: course3,
    courseName: "Web Development",
    price: "80.00",
    percentage:"91",
    status: "In Progress",
    color: "John Doe",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  
 
];
// =================== PaginationItems End here =================
